---
- name: Install watchman (OS X)
  homebrew_cask: name=watchman state=present
  when: ansible_os_family == 'Darwin'

- name: Install watchman (Arch)
  pacman: name=watchman state=present
  when: ansible_os_family == 'Archlinux'
