---
- name: Install kwm
  homebrew: name=koekeishiya/kwm/kwm state=present
  when: ansible_os_family == 'Darwin'

- name: Create config dir
  file: path=~/.kwm state=directory mode=0755

- name: Write kwm config
  copy: src=kwmrc dest=~/.kwm/kwmrc

- name: Enable kwm on login
  commad: brew services start homebrew/binary/kwm
